# SITE CONFIGURATION
title: Mapea tu Cuadra
author: Codeando México
description: > # Meta description of Homepage
  Mapea tu Cuadra, es una iniciativa de URBE León en colaboración con Codeando México, para mapear la infraestructura de micromovilidad en las ciudades.
baseurl: "" # the subpath of your site, e.g. /blog
url: "mapeatucuadra.org" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: URBE León
  links:
    - https://twitter.com/urbe_leon
    - https://www.facebook.com/UrbeLeon
    - https://github.com/CodeandoMexico/mapea-tu-cuadra
    - https://codeandomexico.org/

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Inicio', link: '/'}
  - {name: 'Convocatoria', link: '/convocatoria'}
  - {name: 'Registro', link: '/registro'}

tagline: >
  Proyecto de evaluación de la movilidad peatonal y ciclista

hero_img: maps/map14.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: equipo@codeandomexico.org # email for form submission

twitter_username: urbe_leon # replace with your_twitter_username or comment to remove link from footer
github_username:  codeandomexico/mapea-tu-cuadra # replace with your_github_username or comment to remove link from footer
instagram_username: urbe_leon # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: janczizikow # to enable comments replace with your_disqus_shortname

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
